### ISSUE TITLE
cannot load such file -- capistrano/git_copy/utility

### ISSUE THREAD

**Issue by hiroyuki-sato** [ydkn/capistrano-git-copy-bundle#2]
Hello 

I got the following error.

```
cannot load such file -- capistrano/git_copy/utility
```

It seems that the capistrano-git-copy version 1.3.0 removed that files. 

* capistrano-git-copy: 1.3.0
* capistrano-git-copy-bundle: 0.1.0

**Comment by ydkn** [comment]
Hi,

I haven't used this gem in a while so I missed the dependency to _git-copy_.
I now have removed it as a dependency so this won't be a problem in the future.

Give it a try and let me know if it works again.

**Comment by hiroyuki-sato** [comment]
Hello @ydkn 

Thank you so much for your helping.

Could you tell me how to install bundled gems without this gem on your environment?
Are you using internal gem server like geminabox?

Best regards.

**Comment by hiroyuki-sato** [comment]
Thank you for fixing this issue. 

The capistrano-git-copy-bundle 0.2.1 worked as I expected with Capistrano 3.8 and capistrano-git-copy: 1.3.1.

> I haven't used this gem in a while

If possible, could you tell me how to install bundled gems without this gem on your environment?

**Comment by ydkn** [comment]
Hi @hiroyuki-sato 

for my own projects I'm using gemfury and for work a geminabox server. Both options don't require using this gem.

I created it (and use it) for work because we have a few servers inside our customers infrastructure that are very limited in communicating with the internet (due to the requirements of our customers).
Me mentioning that I haven't used it in a while meant only that I had not deployed those installations for a few month now. I have no good suggestion doing it any other way.

I hope this answer helps you.

**Comment by hiroyuki-sato** [comment]
@ydkn 

Thank you for sharing your knowledge. 
It's a simple way for install gem.

I thought you are using alternative gem instead of this project. 

Anyway, thank you for fixing the issue.
I am also using geminabox,
but I wanted to use this gem for deploy app which can't connect to internal geminabox server. 

Thanks again.
